<<<<<<< HEAD
# Enable stateless CSRF protection for forms and logins/logouts
framework:
    form:
        csrf_protection:
            token_id: submit

    csrf_protection:
        stateless_token_ids:
            - submit
            - authenticate
            - logout
=======

>>>>>>> b2f43ba2c3b18bebe120cab4f5fa1f2e65b267bc
