# Ce fichier contrôle la configuration des routes
# Importez les routes des contrôleurs automatiquement

# Import des contrôleurs (déjà présent)
controllers:
    resource: ../src/Controller/
    type: attribute

## Les routes front/admin sont définies dans les contrôleurs (attributs).